[package]
name = "raspi4-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
board_qemu = []
board_raspi4 = []


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
